Ligi={"Ekstraklasa":["Raków Częstochowa",
"Legia Warszawa",
"Widzew Łódź",
"Pogoń Szczecin",
"Wisła Płock",
"Lech Poznań",
"Stal Mielec",
"Cracovia",
"Warta Poznań",
"Radomiak Radom",
"Śląsk Wrocław",
"Górnik Zabrze",
"Jagiellonia Białystok",
"KS Lechia Gdańsk",
"Zagłębie Lubin",
"Piast Gliwice",
"MKS Korona Kielce",
"Miedź Legnica"],"Bundesliga":["Bayern Monachium",
"Eintracht Frankfurt",
"FC Union Berlin",
"SC Freiburg",
"RB Lipsk",
"Borussia Dortmund",
"VfL Wolfsburg",
"Borussia Mgladbach",
"Bayer Leverkusen",
"Werder Brema",
"FC Köln",
"FSV Mainz 05",
"Hoffenheim",
"VfL Bochum",
"VfB Stuttgard",
"FC Augsburg",
"Hertha Berlin",
"Schalke 04"],"LaLiga": ["Barcelona",
"Real Madryt",
"Real Sociedad",
"Atl. Madryt",
"Villarreal",
"Betis",
"Osasuna",
"Ath. Bilbao",
"Vallecano",
"Mallorca",
"Girona",
"Valencia",
"Espanyol",
"Almeria",
"Sevilla",
"Getafe",
"Celta Vigo",
"Valladolid",
"Cadiz",
"Elche"],"Premier League":["Arsenal",
"Manchester City",
"Newcastle",
"Manchester Utd",
"Tottenham",
"Brighton",
"Fulham",
"Brentford",
"Liverpool",
"Chelsea",
"Aston Villa",
"Crystal Palace",
"Nottingham",
"Leicester",
"Leeds",
"West Ham",
"Wolves",
"Bournemouth",
"Everton",
"Southampton"] }