Ligi={"Ekstraklasa":["Raków Częstochowa",
"Legia Warszawa",
"Widzew Łódź",
"Pogoń Szczecin",
"Wisła Płock",
"Lech Poznań",
"Stal Mielec",
"Cracovia",
"Warta Poznań",
"Radomiak Radom",
"Śląsk Wrocław",
"Górnik Zabrze",
"Jagiellonia Białystok",
"KS Lechia Gdańsk",
"Zagłębie Lubin",
"Piast Gliwice",
"MKS Korona Kielce",
"Miedź Legnica"],"Bundesliga":["Bayern Monachium",
"Eintracht Frankfurt",
"FC Union Berlin",
"SC Freiburg",
"RB Lipsk",
"Borussia Dortmund",
"VfL Wolfsburg",
"Borussia M'gladbach",
"Bayer Leverkusen",
"Werder Brema",
"FC Köln",
"FSV Mainz 05",
"Hoffenheim",
"VfL Bochum",
"VfB Stuttgard",
"FC Augsburg",
"Hertha Berlin",
"Schalke 04"] }